sudo: required
language: generic

services:
- docker

before_script:
- curl -sSLf https://get.docker.com | sed s/sleep\ 20/sleep\ 0/g | sudo -E sh

script:
  - make build
  - make build_samples
  - ./test/version.sh ./faas-cli

after_success:
    - if [ ! -z "$TRAVIS_TAG" ] ; then
        if [ -z "$DOCKER_NS" ] ; then
          export DOCKER_NS=utsavanand2;
        fi;

        docker tag openfaas/faas-cli:latest-dev $DOCKER_NS/faas-cli:$TRAVIS_TAG;
        docker tag openfaas/faas-cli:latest-dev $DOCKER_NS/faas-cli:latest;
        docker tag openfaas/faas-cli:latest-dev-root $DOCKER_NS/faas-cli:${TRAVIS_TAG}-root;
        docker tag openfaas/faas-cli:latest-dev-root $DOCKER_NS/faas-cli:latest-root;
        echo $DOCKER_PASSWORD | docker login -u=$DOCKER_NS --password-stdin;
        docker push $DOCKER_NS/faas-cli:$TRAVIS_TAG;
        docker push $DOCKER_NS/faas-cli:latest;
        docker push $DOCKER_NS/faas-cli:${TRAVIS_TAG}-root;
        docker push $DOCKER_NS/faas-cli:latest-root;
      fi;

before_deploy:
  - make build_redist
  - make test-templating
  - ./ci/hashgen.sh

deploy:
  provider: releases
  api_key:
      secure: "JuNz3yqHFhf+F/qWXVnwE8ju85FL32kkbL601rfz1/kvtyJ1a1jlR3UoLrp2Zv2nUl3ZZOf3kjsFWvnRXQmsE7sfenFGIr4rj9peySiqbpYK0WmsEDf50DcR21bDm1PplNJj9Cj/vd03rFUGwPRrFTxpLY7pGgCubINqk4fTaCMIsdKZQC2d0EfZVSgLZMhALehOHiPuqSCgJnTq8CW3ISOlolVHfMRsj6J1O0Q1T96DRgl4qd3tfgA5PSfklM3CUh7+n1nfZgf+mMs5M924Rx259nxMLPPrqgdD70H6jmrU1Qm0mv9fM4qs425ZWO9pptVJ4umw+F6ahQ8xd4K0RWc3sN/ASV2RrFRggR/k6fRlY8a39HU/FOurRTWFlBQQwXAfl+caGn7zCaRwru4ctW0dxFX7VSB83bKBqL6WG8Qv6yIgfInTGeWsBmtZYg3lnY5FZt/seQD7MrkIlaP17Fc5FKr+GOlTSVrqIj/5gwqU6Q9mLFxPhgAm7GRmVzUy7o4jECb7EPkuh75398w6HnLHMgcs/hqU0lh0aVW/yQ6Wi7qWWBBZLe1if2X7NXUCk2LYtRQbYvmLCdPbIzHYWl/TXzVH00T/ePed2sveW/jpsvv6jurCcy5JdfWqnsNTv05SY1fyJK3yEstfU6F8dzem5DhTJVyHIdhHmirWX/0="
  file: 
  - faas-cli
  - faas-cli-darwin
  - faas-cli-armhf
  - faas-cli.exe
  - faas-cli-arm64
  - faas-cli.sha256
  - faas-cli-darwin.sha256
  - faas-cli-armhf.sha256
  - faas-cli.exe.sha256
  - faas-cli-arm64.sha256
  skip_cleanup: true
  on:
    tags: true

env:
  - GO111MODULE=off
