name: ci-only

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@master
        with:
            fetch-depth: 1
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Local docker build (non-root image)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false
          platforms: linux/amd64
          target: release
          load: true
          tags: utsavanand2/faas-cli:${{ github.sha }}
      - 
        name: Local docker build (root image)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false
          platforms: linux/amd64
          target: release
          tags: utsavanand2/faas-cli:${{ github.sha }}-root
      - 
        name: Copy binary to host
        run: |
          docker create --name faas-cli utsavanand2/faas-cli:${{ github.sha }} && \
          docker cp faas-cli:/usr/bin/faas-cli . && \
          docker rm -f faas-cli
      - 
        name: Build samples
        run: ./build_samples.sh
      - 
        name: Test version
        run: ./test/version.sh ./faas-cli
      - 
        name: Test the cli and the function behaviour
        run: make test-templating
