name: publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - 
        name: Get tags
        id: get_tag
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - 
        name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and Push container images (non-root)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          target: release
          push: true
          tags: |
            utsavanand2/faas-cli:${{ steps.get_tag.outputs.TAG }}
            utsavanand2/faas-cli:latest
            ghcr.io/utsavanand2/faas-cli:${{ steps.get_tag.outputs.TAG }}
            ghcr.io/utsavanand2/faas-cli:latest
      - 
        name: Build and Push container images (root)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          target: root
          push: true
          tags: |
            utsavanand2/faas-cli:${{ steps.get_tag.outputs.TAG }}-root
            utsavanand2/faas-cli:latest-root
            ghcr.io/utsavanand2/faas-cli:${{ steps.get_tag.outputs.TAG }}-root
            ghcr.io/utsavanand2/faas-cli:latest-root
      -
        name: Build binaries for multiple environments
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.redist
          platforms: linux/amd64
          push: false
          tags: |
            utsavanand2/faas-cli:${{ steps.get_tag.outputs.TAG }}
      - 
        name: Copy binaries to host
        run: |
          docker create --name faas-cli openfaas/faas-cli:${{ steps.get_tag.outputs.TAG }} && \
          docker cp faas-cli:/home/app/faas-cli ./bin && \
          docker cp faas-cli:/home/app/faas-cli-darwin ./bin && \
          docker cp faas-cli:/home/app/faas-cli-armhf ./bin && \
          docker cp faas-cli:/home/app/faas-cli-arm64 ./bin && \
          docker cp faas-cli:/home/app/faas-cli.exe ./bin && \
          docker rm -f faas-cli
      - 
        name: Create SHA of binaries
        run: ./hashgen.sh
      - 
        name: Upload binaries and their SHA to Github Release
        uses: alexellis/upload-assets@0.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["./bin/faas-cli*"]'
